# See here for image contents: https://github.com/devcontainers/images/blob/main/src/dotnet/.devcontainer/Dockerfile
# Example of using a preview version: mcr.microsoft.com/devcontainers/dotnet:10.0-preview

FROM mcr.microsoft.com/vscode/devcontainers/dotnet:latest
