
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Sonar Code Smell", "S101:Types should be named in camel case", Justification = "Acceptable use of common initialism", Scope = "type", Target = "~T:Microsoft.IdentityModel.Clients.ActiveDirectory.WebUIFactory")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Sonar Code Smell", "S101:Types should be named in camel case", Justification = "Acceptable use of common initialism", Scope = "type", Target = "~T:Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.SilentWebUIDoneEventArgs")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Sonar Code Smell", "S101:Types should be named in camel case", Justification = "Type matches Interop name", Scope = "type", Target = "~T:Microsoft.IdentityModel.Clients.ActiveDirectory.Native.BCryptNative.BCRYPT_AUTHENTICATED_CIPHER_MODE_INFO")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Sonar Code Smell", "S101:Types should be named in camel case", Justification = "Type matches Interop name", Scope = "type", Target = "~T:Microsoft.IdentityModel.Clients.ActiveDirectory.Native.BCryptNative.BCRYPT_KEY_DATA_BLOB")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Sonar Code Smell", "S101:Types should be named in camel case", Justification = "Type matches Interop name", Scope = "type", Target = "~T:Microsoft.IdentityModel.Clients.ActiveDirectory.Native.BCryptNative.BCRYPT_KEY_LENGTHS_STRUCT")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Sonar Code Smell", "S101:Types should be named in camel case", Justification = "Type matches Interop name", Scope = "type", Target = "~T:Microsoft.IdentityModel.Clients.ActiveDirectory.Native.BCryptNative.BCRYPT_OAEP_PADDING_INFO")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Sonar Code Smell", "S101:Types should be named in camel case", Justification = "Type matches Interop name", Scope = "type", Target = "~T:Microsoft.IdentityModel.Clients.ActiveDirectory.Native.BCryptNative.BCRYPT_PKCS1_PADDING_INFO")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Sonar Code Smell", "S101:Types should be named in camel case", Justification = "Type matches Interop name", Scope = "type", Target = "~T:Microsoft.IdentityModel.Clients.ActiveDirectory.Native.BCryptNative.BCRYPT_PSS_PADDING_INFO")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Sonar Code Smell", "S101:Types should be named in camel case", Justification = "Type matches Interop name", Scope = "type", Target = "~T:Microsoft.IdentityModel.Clients.ActiveDirectory.Native.BCryptNative.BCRYPT_RSAKEY_BLOB")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Sonar Code Smell", "S101:Types should be named in camel case", Justification = "Type matches Interop name", Scope = "type", Target = "~T:Microsoft.IdentityModel.Clients.ActiveDirectory.Native.Win32Native.SYSTEMTIME")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Sonar Code Smell", "S101:Types should be named in camel case", Justification = "Type matches Interop name", Scope = "type", Target = "~T:Microsoft.IdentityModel.Clients.ActiveDirectory.PlatformInformation.NativeMethods.SYSTEM_INFO")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Sonar Code Smell", "S101:Types should be named in camel case", Justification = "Type matches Interop name", Scope = "type", Target = "~T:Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.NativeWrapper.COMRECT")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Sonar Code Smell", "S101:Types should be named in camel case", Justification = "Type matches Interop name", Scope = "type", Target = "~T:Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.NativeWrapper.DOCHOSTUIINFO")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Sonar Code Smell", "S101:Types should be named in camel case", Justification = "Type matches Interop name", Scope = "type", Target = "~T:Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.NativeWrapper.MSG")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Sonar Code Smell", "S101:Types should be named in camel case", Justification = "Type matches Interop name", Scope = "type", Target = "~T:Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.NativeWrapper.OLECMD")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Sonar Code Smell", "S101:Types should be named in camel case", Justification = "Type matches Interop name", Scope = "type", Target = "~T:Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.NativeWrapper.POINT")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Sonar Code Smell", "S101:Types should be named in camel case", Justification = "Type matches Interop name", Scope = "type", Target = "~T:Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.NativeWrapper.tagOleMenuGroupWidths")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Sonar Code Smell", "S107:Methods should not have too many parameters", Justification = "Signature required to match interop function", Scope = "member", Target = "~M:Microsoft.IdentityModel.Clients.ActiveDirectory.Native.NCryptNative.UnsafeNativeMethods.NCryptSignHash(Microsoft.Win32.SafeHandles.SafeNCryptKeyHandle,Microsoft.IdentityModel.Clients.ActiveDirectory.Native.BCryptNative.BCRYPT_PKCS1_PADDING_INFO@,System.Byte[],System.Int32,System.Byte[],System.Int32,System.Int32@,Microsoft.IdentityModel.Clients.ActiveDirectory.Native.AsymmetricPaddingMode)~Microsoft.IdentityModel.Clients.ActiveDirectory.Native.NCryptNative.ErrorCode")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Sonar Code Smell", "S107:Methods should not have too many parameters", Justification = "Signature required to match interop function", Scope = "member", Target = "~M:Microsoft.IdentityModel.Clients.ActiveDirectory.Native.NCryptNative.UnsafeNativeMethods.NCryptSignHash(Microsoft.Win32.SafeHandles.SafeNCryptKeyHandle,Microsoft.IdentityModel.Clients.ActiveDirectory.Native.BCryptNative.BCRYPT_PSS_PADDING_INFO@,System.Byte[],System.Int32,System.Byte[],System.Int32,System.Int32@,Microsoft.IdentityModel.Clients.ActiveDirectory.Native.AsymmetricPaddingMode)~Microsoft.IdentityModel.Clients.ActiveDirectory.Native.NCryptNative.ErrorCode")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Sonar Code Smell", "S107:Methods should not have too many parameters", Justification = "Signature required to match interop function", Scope = "type", Target = "~T:Microsoft.IdentityModel.Clients.ActiveDirectory.Native.NCryptNative.NCryptDecryptor`1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Sonar Code Smell", "S107:Methods should not have too many parameters", Justification = "Signature required to match interop function", Scope = "type", Target = "~T:Microsoft.IdentityModel.Clients.ActiveDirectory.Native.NCryptNative.NCryptEncryptor`1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Sonar Code Smell", "S107:Methods should not have too many parameters", Justification = "Signature required to match interop function", Scope = "type", Target = "~T:Microsoft.IdentityModel.Clients.ActiveDirectory.Native.NCryptNative.NCryptHashSigner`1")]