name: Code Coverage

permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    continue-on-error: true
    name: MSAL GitHub Actions
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.1

    - name: Setup .NET 6.0.x
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: 6.0.x

    - name: Create code coverage report
      run: |
        dotnet tool install -g dotnet-reportgenerator-globaltool
        reportgenerator -reports:./**/coverage.cobertura.xml -targetdir:CodeCoverage -reporttypes:'MarkdownSummaryGithub;Cobertura'

    - name: Write Coverage to Job Summary
      shell: bash
      run: |
        cat CodeCoverage/SummaryGithub.md >> $GITHUB_STEP_SUMMARY
        echo "COMMENT_CONTENT_ENV_VAR<<EOF" >> $GITHUB_ENV
        echo $(cat CodeCoverage/SummaryGithub.md) >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Comment Coverage in PR
      uses: actions/github-script@v7
      id: comment
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: process.env.COMMENT_CONTENT_ENV_VAR
          })
