# .github/workflows/spellcheck.yml
name: Spell check
on: [pull_request]

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      ############################################################
      # 1️⃣  Built-in codespell action  → PR annotations
      ############################################################
      - name: Codespell (built-in dictionary)
        uses: codespell-project/actions-codespell@0c1b7db3ec1527186e897b0ebee1736475623fca
        with:
          check_filenames: true           # also scan file names
          ignore_words_file: .codespellignore
          skip: >
            src/client/Microsoft.Identity.Client/json,
            tests,
            devapps,
            build,
            docs,
            prototype,

      ############################################################
      # 2️⃣  Raw CLI pass  → enforces your custom typo pairs
      ############################################################
      - name: Install codespell
        run: pip install --quiet --no-deps "codespell==2.4.1"

      - name: Codespell (custom pair list)
        run: |
          codespell --check-filenames \
            --dictionary build/codespell_pairs.txt \
            --ignore-words .codespellignore \
            --skip "src/client/Microsoft.Identity.Client/json,tests,devapps,build,docs,prototype" \
            .
